# Exploratory Data Analysis and Visualization (in Python)

**NOTE: this is an early work in progress. Check back shortly for new additions.**

## Introduction 

The purpose of this document is to serve as a smorgasbord of EDA techniques and visualization tools. 

Once I have had some time to more thoroughly flesh out this document, it will more closely resemble the [other markdowns that I have up on GitHub]('https://github.com/pmaji/data-science-toolkit/blob/master/classification/logit/logistic_regression.md') that are much more neatly organized.

The counterpart to this notebook--written in R--can [be found here]('https://github.com/pmaji/data-science-toolkit/blob/master/eda-and-visualization/eda_and_visualization.md').

## Setup 

To enable toggle-able table of contents (with button to enable / disable), check out [this link here]('https://github.com/minrk/ipython_extensions') for instructions on how to get set up.

In [1]:
import datetime
# prints the present date and time as a form of log
print("This notebook was late run: ", datetime.datetime.now())

This notebook was late run:  2019-01-16 11:23:15.523001

In [2]:
# key libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
# cd to correct directory 
%cd '/Users/pauljeffries/Desktop/personal/personal_code/data-science-toolkit-master' 
# print working directory just be sure
%pwd

/Users/pauljeffries/Desktop/personal/personal_code/data-science-toolkit-master

'/Users/pauljeffries/Desktop/personal/personal_code/data-science-toolkit-master'

## Importing, Exploring, and Cleaning the Data

### Importing the Data

The data used in this document come from a [Kaggle post](https://www.kaggle.com/kemical/kickstarter-projects/home) focused on Kickstarter campaigns. If unfamiliar with the notion of a Kickstarter campaign (henceforth just campaign), I would recommend reading [this FAQ here](https://help.kickstarter.com/hc/en-us/categories/115000499013-Kickstarter-basics). I will not spend a great deal of time explaining the data, so for more information on the data specifically, I recommend reading the detailed exploration on the [data page for this Kaggle](https://www.kaggle.com/kemical/kickstarter-projects).

In [11]:
# importing the dataset from the CSV
base_df = pd.read_csv(filepath_or_buffer = 'hypothesis-tests/data/ks-projects-201801.csv')

# print the head of the base dataframe
base_df.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00

### Exploring the Data

In [18]:
# building a helpful function to look get info on the columns in our data frame
def dataframe_explorer(df):
    dict_list = []
    for col in df.columns:
        data = df[col]
        dict_ = {}
        # pulls the null count for a column
        dict_.update({'null_count' : data.isnull().sum()})
        # counts the unique values in a column
        dict_.update({'unique_count' : len(data.unique())})
        # gets the types of the data in a column
        dict_.update({'data_type' : data.dtype})
        dict_list.append(dict_)
            
    col_info_df = pd.DataFrame(dict_list)
    col_info_df.index = df.columns
    col_info_df.sort_values(by=['null_count','unique_count'], ascending=[True, False], inplace=True)
        
    return col_info_df

In [19]:
# checking out our data with the the dataframe explorer
dataframe_explorer(base_df)

                 data_type  null_count  unique_count
ID                   int64           0        378661
launched            object           0        378089
usd_pledged_real   float64           0        106065
pledged            float64           0         62130
usd_goal_real      float64           0         50339
goal               float64           0          8353
backers              int64           0          3963
deadline            object           0          3164
category            object           0           159
country             object           0            23
main_category       object           0            15
currency            object           0            14
state               object           0             6
name                object           4        375765
usd pledged        float64        3797         95456